server:
  port: 7777

#Redisson单机配置
spring:
    redis:
      database: 0
      host:
      port: 6379
      password:
      jedis:
        pool:
          max-idle: 10
          max-active: 10
          min-idle: 200